# Generated by Django 3.0.7 on 2023-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=255)),
                ('order_id', models.CharField(db_index=True, max_length=255)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('time_stamp', models.IntegerField()),
                ('type', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], default='sell', max_length=4)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
